### ISSUE TITLE
[Bug]wifi ap, no notification

### ISSUE THREAD

**Issue by ddijanic** [BlueAndi/Pixelix#202]
greeting.
I noticed that on the new version. I don't know exactly from which version exactly.

in wifi AP mode, there is no notification to click and set wifi.
but you have to go to the web browser and type in the IP yourself.

Esp dev 1
Latest relise

**Comment by BlueAndi** [comment]
Hi, which mobile device OS do you have (Android, IOS)? And with the same mobile device, it works with an older Pixelix version? Which one is it?

**Comment by BlueAndi** [comment]
And can you try with the Development branch and show the logs here, which are printed?

**Comment by BlueAndi** [comment]
No response, issue closed.
