### ISSUE TITLE
[Bug] Brightness control with 1 button setup doesnt work as intended

### ISSUE THREAD

**Issue by Leeefy** [BlueAndi/Pixelix#210]
**Expected behavior:**
Holding down the button increases the brightness then decreases it. It should increase a second time, therefore making it into a loop (as described here: https://github.com/BlueAndi/Pixelix/tree/Development?tab=readme-ov-file#user-interface)
**Actual behavior:**
Holding down the button increases the brightness then decreases it. It doesn't increase a second time, therefore not making it into a loop. 

**More Information**
 - Development board: ESP32-DevKit-v1
 - Versions: 8.0.0, 7.2.5, 7.2.4 (Release versions I have used before)

**Comment by BlueAndi** [comment]
Fixed in Development branch, please verify.

**Comment by Leeefy** [comment]
Works as intended now!
